package com.ailu.firmoffer.dao.bean;

import java.math.BigDecimal;
import java.util.Date;

public class FirmOfferExchangeBenifitHour {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_benifit_hour.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_benifit_hour.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_benifit_hour.total
     *
     * @mbg.generated
     */
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_benifit_hour.future
     *
     * @mbg.generated
     */
    private BigDecimal future;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_benifit_hour.wallet
     *
     * @mbg.generated
     */
    private BigDecimal wallet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_benifit_hour.stock
     *
     * @mbg.generated
     */
    private BigDecimal stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_benifit_hour.margin
     *
     * @mbg.generated
     */
    private BigDecimal margin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_benifit_hour.time_number
     *
     * @mbg.generated
     */
    private Long timeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_benifit_hour.ctime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_benifit_hour.utime
     *
     * @mbg.generated
     */
    private Date utime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_benifit_hour.id
     *
     * @return the value of firm_offer_exchange_benifit_hour.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_benifit_hour.id
     *
     * @param id the value for firm_offer_exchange_benifit_hour.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_benifit_hour.user_id
     *
     * @return the value of firm_offer_exchange_benifit_hour.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_benifit_hour.user_id
     *
     * @param userId the value for firm_offer_exchange_benifit_hour.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_benifit_hour.total
     *
     * @return the value of firm_offer_exchange_benifit_hour.total
     *
     * @mbg.generated
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_benifit_hour.total
     *
     * @param total the value for firm_offer_exchange_benifit_hour.total
     *
     * @mbg.generated
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_benifit_hour.future
     *
     * @return the value of firm_offer_exchange_benifit_hour.future
     *
     * @mbg.generated
     */
    public BigDecimal getFuture() {
        return future;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_benifit_hour.future
     *
     * @param future the value for firm_offer_exchange_benifit_hour.future
     *
     * @mbg.generated
     */
    public void setFuture(BigDecimal future) {
        this.future = future;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_benifit_hour.wallet
     *
     * @return the value of firm_offer_exchange_benifit_hour.wallet
     *
     * @mbg.generated
     */
    public BigDecimal getWallet() {
        return wallet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_benifit_hour.wallet
     *
     * @param wallet the value for firm_offer_exchange_benifit_hour.wallet
     *
     * @mbg.generated
     */
    public void setWallet(BigDecimal wallet) {
        this.wallet = wallet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_benifit_hour.stock
     *
     * @return the value of firm_offer_exchange_benifit_hour.stock
     *
     * @mbg.generated
     */
    public BigDecimal getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_benifit_hour.stock
     *
     * @param stock the value for firm_offer_exchange_benifit_hour.stock
     *
     * @mbg.generated
     */
    public void setStock(BigDecimal stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_benifit_hour.margin
     *
     * @return the value of firm_offer_exchange_benifit_hour.margin
     *
     * @mbg.generated
     */
    public BigDecimal getMargin() {
        return margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_benifit_hour.margin
     *
     * @param margin the value for firm_offer_exchange_benifit_hour.margin
     *
     * @mbg.generated
     */
    public void setMargin(BigDecimal margin) {
        this.margin = margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_benifit_hour.time_number
     *
     * @return the value of firm_offer_exchange_benifit_hour.time_number
     *
     * @mbg.generated
     */
    public Long getTimeNumber() {
        return timeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_benifit_hour.time_number
     *
     * @param timeNumber the value for firm_offer_exchange_benifit_hour.time_number
     *
     * @mbg.generated
     */
    public void setTimeNumber(Long timeNumber) {
        this.timeNumber = timeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_benifit_hour.ctime
     *
     * @return the value of firm_offer_exchange_benifit_hour.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_benifit_hour.ctime
     *
     * @param ctime the value for firm_offer_exchange_benifit_hour.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_benifit_hour.utime
     *
     * @return the value of firm_offer_exchange_benifit_hour.utime
     *
     * @mbg.generated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_benifit_hour.utime
     *
     * @param utime the value for firm_offer_exchange_benifit_hour.utime
     *
     * @mbg.generated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }
}