package com.ailu.firmoffer.dao.bean;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class FirmOfferPushHist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_push_hist.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_push_hist.exchange
     *
     * @mbg.generated
     */
    private String exchange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_push_hist.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_push_hist.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_push_hist.symbol
     *
     * @mbg.generated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_push_hist.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_push_hist.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_push_hist.utime
     *
     * @mbg.generated
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_push_hist.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_push_hist.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_push_hist.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_push_hist.order_status
     *
     * @mbg.generated
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_push_hist.show_status
     *
     * @mbg.generated
     */
    private Integer showStatus;

    private String UserName;


    private Long mTime;
}