package com.ailu.firmoffer.dao.bean;

import java.math.BigDecimal;
import java.util.Date;

public class FirmOfferLedgerHist2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_ledger_hist2.ledger_id
     *
     * @mbg.generated
     */
    private String ledgerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_ledger_hist2.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_ledger_hist2.exchange
     *
     * @mbg.generated
     */
    private String exchange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_ledger_hist2.currency
     *
     * @mbg.generated
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_ledger_hist2.balance
     *
     * @mbg.generated
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_ledger_hist2.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_ledger_hist2.type_name
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_ledger_hist2.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_ledger_hist2.fee
     *
     * @mbg.generated
     */
    private BigDecimal fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_ledger_hist2.timestamp
     *
     * @mbg.generated
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_ledger_hist2.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_ledger_hist2.uTime
     *
     * @mbg.generated
     */
    private Date utime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_ledger_hist2.ledger_id
     *
     * @return the value of firm_offer_ledger_hist2.ledger_id
     *
     * @mbg.generated
     */
    public String getLedgerId() {
        return ledgerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_ledger_hist2.ledger_id
     *
     * @param ledgerId the value for firm_offer_ledger_hist2.ledger_id
     *
     * @mbg.generated
     */
    public void setLedgerId(String ledgerId) {
        this.ledgerId = ledgerId == null ? null : ledgerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_ledger_hist2.user_id
     *
     * @return the value of firm_offer_ledger_hist2.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_ledger_hist2.user_id
     *
     * @param userId the value for firm_offer_ledger_hist2.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_ledger_hist2.exchange
     *
     * @return the value of firm_offer_ledger_hist2.exchange
     *
     * @mbg.generated
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_ledger_hist2.exchange
     *
     * @param exchange the value for firm_offer_ledger_hist2.exchange
     *
     * @mbg.generated
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_ledger_hist2.currency
     *
     * @return the value of firm_offer_ledger_hist2.currency
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_ledger_hist2.currency
     *
     * @param currency the value for firm_offer_ledger_hist2.currency
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_ledger_hist2.balance
     *
     * @return the value of firm_offer_ledger_hist2.balance
     *
     * @mbg.generated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_ledger_hist2.balance
     *
     * @param balance the value for firm_offer_ledger_hist2.balance
     *
     * @mbg.generated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_ledger_hist2.amount
     *
     * @return the value of firm_offer_ledger_hist2.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_ledger_hist2.amount
     *
     * @param amount the value for firm_offer_ledger_hist2.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_ledger_hist2.type_name
     *
     * @return the value of firm_offer_ledger_hist2.type_name
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_ledger_hist2.type_name
     *
     * @param typeName the value for firm_offer_ledger_hist2.type_name
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_ledger_hist2.type
     *
     * @return the value of firm_offer_ledger_hist2.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_ledger_hist2.type
     *
     * @param type the value for firm_offer_ledger_hist2.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_ledger_hist2.fee
     *
     * @return the value of firm_offer_ledger_hist2.fee
     *
     * @mbg.generated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_ledger_hist2.fee
     *
     * @param fee the value for firm_offer_ledger_hist2.fee
     *
     * @mbg.generated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_ledger_hist2.timestamp
     *
     * @return the value of firm_offer_ledger_hist2.timestamp
     *
     * @mbg.generated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_ledger_hist2.timestamp
     *
     * @param timestamp the value for firm_offer_ledger_hist2.timestamp
     *
     * @mbg.generated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_ledger_hist2.status
     *
     * @return the value of firm_offer_ledger_hist2.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_ledger_hist2.status
     *
     * @param status the value for firm_offer_ledger_hist2.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_ledger_hist2.uTime
     *
     * @return the value of firm_offer_ledger_hist2.uTime
     *
     * @mbg.generated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_ledger_hist2.uTime
     *
     * @param utime the value for firm_offer_ledger_hist2.uTime
     *
     * @mbg.generated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }
}