package com.ailu.firmoffer.dao.bean;

import java.math.BigDecimal;
import java.util.Date;

public class InitUpdate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_update.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_update.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_update.total
     *
     * @mbg.generated
     */
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_update.init
     *
     * @mbg.generated
     */
    private BigDecimal init;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_update.transfer_price
     *
     * @mbg.generated
     */
    private BigDecimal transferPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_update.final_init
     *
     * @mbg.generated
     */
    private BigDecimal finalInit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column init_update.cTime
     *
     * @mbg.generated
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_update.id
     *
     * @return the value of init_update.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_update.id
     *
     * @param id the value for init_update.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_update.user_id
     *
     * @return the value of init_update.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_update.user_id
     *
     * @param userId the value for init_update.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_update.total
     *
     * @return the value of init_update.total
     *
     * @mbg.generated
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_update.total
     *
     * @param total the value for init_update.total
     *
     * @mbg.generated
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_update.init
     *
     * @return the value of init_update.init
     *
     * @mbg.generated
     */
    public BigDecimal getInit() {
        return init;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_update.init
     *
     * @param init the value for init_update.init
     *
     * @mbg.generated
     */
    public void setInit(BigDecimal init) {
        this.init = init;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_update.transfer_price
     *
     * @return the value of init_update.transfer_price
     *
     * @mbg.generated
     */
    public BigDecimal getTransferPrice() {
        return transferPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_update.transfer_price
     *
     * @param transferPrice the value for init_update.transfer_price
     *
     * @mbg.generated
     */
    public void setTransferPrice(BigDecimal transferPrice) {
        this.transferPrice = transferPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_update.final_init
     *
     * @return the value of init_update.final_init
     *
     * @mbg.generated
     */
    public BigDecimal getFinalInit() {
        return finalInit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_update.final_init
     *
     * @param finalInit the value for init_update.final_init
     *
     * @mbg.generated
     */
    public void setFinalInit(BigDecimal finalInit) {
        this.finalInit = finalInit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column init_update.cTime
     *
     * @return the value of init_update.cTime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column init_update.cTime
     *
     * @param ctime the value for init_update.cTime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}