package com.ailu.firmoffer.dao.bean;

import java.math.BigDecimal;
import java.util.Date;

public class UserInit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_init.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_init.balance
     *
     * @mbg.generated
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_init.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_init.uTime
     *
     * @mbg.generated
     */
    private Date utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_init.benifit_time
     *
     * @mbg.generated
     */
    private Date benifitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_init.init_origin
     *
     * @mbg.generated
     */
    private BigDecimal initOrigin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_init.id
     *
     * @return the value of user_init.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_init.id
     *
     * @param id the value for user_init.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_init.balance
     *
     * @return the value of user_init.balance
     *
     * @mbg.generated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_init.balance
     *
     * @param balance the value for user_init.balance
     *
     * @mbg.generated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_init.user_id
     *
     * @return the value of user_init.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_init.user_id
     *
     * @param userId the value for user_init.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_init.uTime
     *
     * @return the value of user_init.uTime
     *
     * @mbg.generated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_init.uTime
     *
     * @param utime the value for user_init.uTime
     *
     * @mbg.generated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_init.benifit_time
     *
     * @return the value of user_init.benifit_time
     *
     * @mbg.generated
     */
    public Date getBenifitTime() {
        return benifitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_init.benifit_time
     *
     * @param benifitTime the value for user_init.benifit_time
     *
     * @mbg.generated
     */
    public void setBenifitTime(Date benifitTime) {
        this.benifitTime = benifitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_init.init_origin
     *
     * @return the value of user_init.init_origin
     *
     * @mbg.generated
     */
    public BigDecimal getInitOrigin() {
        return initOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_init.init_origin
     *
     * @param initOrigin the value for user_init.init_origin
     *
     * @mbg.generated
     */
    public void setInitOrigin(BigDecimal initOrigin) {
        this.initOrigin = initOrigin;
    }
}