package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.FirmOfferTransfer;
import com.ailu.firmoffer.dao.bean.FirmOfferTransferExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FirmOfferTransferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_transfer
     *
     * @mbg.generated
     */
    long countByExample(FirmOfferTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_transfer
     *
     * @mbg.generated
     */
    int deleteByExample(FirmOfferTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_transfer
     *
     * @mbg.generated
     */
    int insert(FirmOfferTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_transfer
     *
     * @mbg.generated
     */
    int insertSelective(FirmOfferTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_transfer
     *
     * @mbg.generated
     */
    List<FirmOfferTransfer> selectByExample(FirmOfferTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_transfer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FirmOfferTransfer record, @Param("example") FirmOfferTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_transfer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FirmOfferTransfer record, @Param("example") FirmOfferTransferExample example);
}