package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.FirmOfferMatchHist;
import com.ailu.firmoffer.dao.bean.FirmOfferMatchHistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FirmOfferMatchHistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    long countByExample(FirmOfferMatchHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    int deleteByExample(FirmOfferMatchHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    int insert(FirmOfferMatchHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    int insertSelective(FirmOfferMatchHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    List<FirmOfferMatchHist> selectByExample(FirmOfferMatchHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    FirmOfferMatchHist selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FirmOfferMatchHist record, @Param("example") FirmOfferMatchHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FirmOfferMatchHist record, @Param("example") FirmOfferMatchHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FirmOfferMatchHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FirmOfferMatchHist record);
}