package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.FirmOfferUserRatioLine;
import com.ailu.firmoffer.dao.bean.FirmOfferUserRatioLineExample;
import com.ailu.firmoffer.service.RateService;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FirmOfferUserRatioLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_user_ratio_line
     *
     * @mbg.generated
     */
    long countByExample(FirmOfferUserRatioLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_user_ratio_line
     *
     * @mbg.generated
     */
    int deleteByExample(FirmOfferUserRatioLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_user_ratio_line
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_user_ratio_line
     *
     * @mbg.generated
     */
    int insert(FirmOfferUserRatioLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_user_ratio_line
     *
     * @mbg.generated
     */
    int insertSelective(FirmOfferUserRatioLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_user_ratio_line
     *
     * @mbg.generated
     */
    List<FirmOfferUserRatioLine> selectByExample(FirmOfferUserRatioLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_user_ratio_line
     *
     * @mbg.generated
     */
    FirmOfferUserRatioLine selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_user_ratio_line
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FirmOfferUserRatioLine record, @Param("example") FirmOfferUserRatioLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_user_ratio_line
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FirmOfferUserRatioLine record, @Param("example") FirmOfferUserRatioLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_user_ratio_line
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FirmOfferUserRatioLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_user_ratio_line
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FirmOfferUserRatioLine record);


    int insertRates(List<RateService.UserRadioLineVo> userRadioLineVos);

}