package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.FirmOfferDepositHist;
import com.ailu.firmoffer.dao.bean.FirmOfferDepositHistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FirmOfferDepositHistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_deposit_hist
     *
     * @mbg.generated
     */
    long countByExample(FirmOfferDepositHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_deposit_hist
     *
     * @mbg.generated
     */
    int deleteByExample(FirmOfferDepositHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_deposit_hist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_deposit_hist
     *
     * @mbg.generated
     */
    int insert(FirmOfferDepositHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_deposit_hist
     *
     * @mbg.generated
     */
    int insertSelective(FirmOfferDepositHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_deposit_hist
     *
     * @mbg.generated
     */
    List<FirmOfferDepositHist> selectByExample(FirmOfferDepositHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_deposit_hist
     *
     * @mbg.generated
     */
    FirmOfferDepositHist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_deposit_hist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FirmOfferDepositHist record, @Param("example") FirmOfferDepositHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_deposit_hist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FirmOfferDepositHist record, @Param("example") FirmOfferDepositHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_deposit_hist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FirmOfferDepositHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_deposit_hist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FirmOfferDepositHist record);
}