package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.FirmOfferMovements;
import com.ailu.firmoffer.dao.bean.FirmOfferMovementsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FirmOfferMovementsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_movements
     *
     * @mbg.generated
     */
    long countByExample(FirmOfferMovementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_movements
     *
     * @mbg.generated
     */
    int deleteByExample(FirmOfferMovementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_movements
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_movements
     *
     * @mbg.generated
     */
    int insert(FirmOfferMovements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_movements
     *
     * @mbg.generated
     */
    int insertSelective(FirmOfferMovements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_movements
     *
     * @mbg.generated
     */
    List<FirmOfferMovements> selectByExample(FirmOfferMovementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_movements
     *
     * @mbg.generated
     */
    FirmOfferMovements selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_movements
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FirmOfferMovements record, @Param("example") FirmOfferMovementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_movements
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FirmOfferMovements record, @Param("example") FirmOfferMovementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_movements
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FirmOfferMovements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_movements
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FirmOfferMovements record);
}