package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.FirmOfferExchangeBenifitHour;
import com.ailu.firmoffer.dao.bean.FirmOfferExchangeBenifitHourExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FirmOfferExchangeBenifitHourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_benifit_hour
     *
     * @mbg.generated
     */
    long countByExample(FirmOfferExchangeBenifitHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_benifit_hour
     *
     * @mbg.generated
     */
    int deleteByExample(FirmOfferExchangeBenifitHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_benifit_hour
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_benifit_hour
     *
     * @mbg.generated
     */
    int insert(FirmOfferExchangeBenifitHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_benifit_hour
     *
     * @mbg.generated
     */
    int insertSelective(FirmOfferExchangeBenifitHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_benifit_hour
     *
     * @mbg.generated
     */
    List<FirmOfferExchangeBenifitHour> selectByExample(FirmOfferExchangeBenifitHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_benifit_hour
     *
     * @mbg.generated
     */
    FirmOfferExchangeBenifitHour selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_benifit_hour
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FirmOfferExchangeBenifitHour record, @Param("example") FirmOfferExchangeBenifitHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_benifit_hour
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FirmOfferExchangeBenifitHour record, @Param("example") FirmOfferExchangeBenifitHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_benifit_hour
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FirmOfferExchangeBenifitHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_benifit_hour
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FirmOfferExchangeBenifitHour record);

    void insertAccounts(List<FirmOfferExchangeBenifitHour> insertList);

    FirmOfferExchangeBenifitHour selectByUserId(FirmOfferExchangeBenifitHour firmOfferExchangeBenifitHour);
}