package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.FirmOfferLedgerHist2;
import com.ailu.firmoffer.dao.bean.FirmOfferLedgerHist2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FirmOfferLedgerHist2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist2
     *
     * @mbg.generated
     */
    long countByExample(FirmOfferLedgerHist2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist2
     *
     * @mbg.generated
     */
    int deleteByExample(FirmOfferLedgerHist2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist2
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String ledgerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist2
     *
     * @mbg.generated
     */
    int insert(FirmOfferLedgerHist2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist2
     *
     * @mbg.generated
     */
    int insertSelective(FirmOfferLedgerHist2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist2
     *
     * @mbg.generated
     */
    List<FirmOfferLedgerHist2> selectByExample(FirmOfferLedgerHist2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist2
     *
     * @mbg.generated
     */
    FirmOfferLedgerHist2 selectByPrimaryKey(String ledgerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist2
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FirmOfferLedgerHist2 record, @Param("example") FirmOfferLedgerHist2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist2
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FirmOfferLedgerHist2 record, @Param("example") FirmOfferLedgerHist2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist2
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FirmOfferLedgerHist2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist2
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FirmOfferLedgerHist2 record);
}