package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.FirmOfferPushHist;
import com.ailu.firmoffer.dao.bean.FirmOfferPushHistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FirmOfferPushHistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_push_hist
     *
     * @mbg.generated
     */
    long countByExample(FirmOfferPushHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_push_hist
     *
     * @mbg.generated
     */
    int deleteByExample(FirmOfferPushHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_push_hist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_push_hist
     *
     * @mbg.generated
     */
    int insert(FirmOfferPushHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_push_hist
     *
     * @mbg.generated
     */
    int insertSelective(FirmOfferPushHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_push_hist
     *
     * @mbg.generated
     */
    List<FirmOfferPushHist> selectByExample(FirmOfferPushHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_push_hist
     *
     * @mbg.generated
     */
    FirmOfferPushHist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_push_hist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FirmOfferPushHist record, @Param("example") FirmOfferPushHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_push_hist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FirmOfferPushHist record, @Param("example") FirmOfferPushHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_push_hist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FirmOfferPushHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_push_hist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FirmOfferPushHist record);
}