package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.FirmOfferOrderHist;
import com.ailu.firmoffer.dao.bean.FirmOfferOrderHistExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FirmOfferOrderHistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    long countByExample(FirmOfferOrderHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    int deleteByExample(FirmOfferOrderHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    int insert(FirmOfferOrderHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    int insertSelective(FirmOfferOrderHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    List<FirmOfferOrderHist> selectByExample(FirmOfferOrderHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    FirmOfferOrderHist selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FirmOfferOrderHist record, @Param("example") FirmOfferOrderHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FirmOfferOrderHist record, @Param("example") FirmOfferOrderHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FirmOfferOrderHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FirmOfferOrderHist record);
}