package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.FirmOfferLedgerHist;
import com.ailu.firmoffer.dao.bean.FirmOfferLedgerHistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FirmOfferLedgerHistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist
     *
     * @mbg.generated
     */
    long countByExample(FirmOfferLedgerHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist
     *
     * @mbg.generated
     */
    int deleteByExample(FirmOfferLedgerHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String ledgerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist
     *
     * @mbg.generated
     */
    int insert(FirmOfferLedgerHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist
     *
     * @mbg.generated
     */
    int insertSelective(FirmOfferLedgerHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist
     *
     * @mbg.generated
     */
    List<FirmOfferLedgerHist> selectByExample(FirmOfferLedgerHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist
     *
     * @mbg.generated
     */
    FirmOfferLedgerHist selectByPrimaryKey(String ledgerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FirmOfferLedgerHist record, @Param("example") FirmOfferLedgerHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FirmOfferLedgerHist record, @Param("example") FirmOfferLedgerHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FirmOfferLedgerHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_ledger_hist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FirmOfferLedgerHist record);
}