package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.FirmOfferExchangeBalanceSnap;
import com.ailu.firmoffer.dao.bean.FirmOfferExchangeBalanceSnapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FirmOfferExchangeBalanceSnapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_snap
     *
     * @mbg.generated
     */
    long countByExample(FirmOfferExchangeBalanceSnapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_snap
     *
     * @mbg.generated
     */
    int deleteByExample(FirmOfferExchangeBalanceSnapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_snap
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_snap
     *
     * @mbg.generated
     */
    int insert(FirmOfferExchangeBalanceSnap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_snap
     *
     * @mbg.generated
     */
    int insertSelective(FirmOfferExchangeBalanceSnap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_snap
     *
     * @mbg.generated
     */
    List<FirmOfferExchangeBalanceSnap> selectByExample(FirmOfferExchangeBalanceSnapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_snap
     *
     * @mbg.generated
     */
    FirmOfferExchangeBalanceSnap selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_snap
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FirmOfferExchangeBalanceSnap record, @Param("example") FirmOfferExchangeBalanceSnapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_snap
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FirmOfferExchangeBalanceSnap record, @Param("example") FirmOfferExchangeBalanceSnapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_snap
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FirmOfferExchangeBalanceSnap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_snap
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FirmOfferExchangeBalanceSnap record);


    void insertAccounts(List<FirmOfferExchangeBalanceSnap> insertList);

    FirmOfferExchangeBalanceSnap selectByUserId(FirmOfferExchangeBalanceSnap firmOfferExchangeBalanceSnap);

}