package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.FirmOfferExchangeBalanceHour;
import com.ailu.firmoffer.dao.bean.FirmOfferExchangeBalanceHourExample;
import java.util.List;

import com.ailu.firmoffer.dao.bean.FirmOfferExchangeBalanceSnap;
import org.apache.ibatis.annotations.Param;

public interface FirmOfferExchangeBalanceHourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_hour
     *
     * @mbg.generated
     */
    long countByExample(FirmOfferExchangeBalanceHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_hour
     *
     * @mbg.generated
     */
    int deleteByExample(FirmOfferExchangeBalanceHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_hour
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_hour
     *
     * @mbg.generated
     */
    int insert(FirmOfferExchangeBalanceHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_hour
     *
     * @mbg.generated
     */
    int insertSelective(FirmOfferExchangeBalanceHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_hour
     *
     * @mbg.generated
     */
    List<FirmOfferExchangeBalanceHour> selectByExample(FirmOfferExchangeBalanceHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_hour
     *
     * @mbg.generated
     */
    FirmOfferExchangeBalanceHour selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_hour
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FirmOfferExchangeBalanceHour record, @Param("example") FirmOfferExchangeBalanceHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_hour
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FirmOfferExchangeBalanceHour record, @Param("example") FirmOfferExchangeBalanceHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_hour
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FirmOfferExchangeBalanceHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_exchange_balance_hour
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FirmOfferExchangeBalanceHour record);

    void insertAccounts(List<FirmOfferExchangeBalanceHour> insertList);

    FirmOfferExchangeBalanceHour selectByUserId(FirmOfferExchangeBalanceHour firmOfferExchangeBalanceHour);
}