package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.InitUpdate;
import com.ailu.firmoffer.dao.bean.InitUpdateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InitUpdateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_update
     *
     * @mbg.generated
     */
    long countByExample(InitUpdateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_update
     *
     * @mbg.generated
     */
    int deleteByExample(InitUpdateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_update
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_update
     *
     * @mbg.generated
     */
    int insert(InitUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_update
     *
     * @mbg.generated
     */
    int insertSelective(InitUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_update
     *
     * @mbg.generated
     */
    List<InitUpdate> selectByExample(InitUpdateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_update
     *
     * @mbg.generated
     */
    InitUpdate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_update
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InitUpdate record, @Param("example") InitUpdateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_update
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InitUpdate record, @Param("example") InitUpdateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_update
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InitUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table init_update
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InitUpdate record);
}