package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.UserInit;
import com.ailu.firmoffer.dao.bean.UserInitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_init
     *
     * @mbg.generated
     */
    long countByExample(UserInitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_init
     *
     * @mbg.generated
     */
    int deleteByExample(UserInitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_init
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_init
     *
     * @mbg.generated
     */
    int insert(UserInit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_init
     *
     * @mbg.generated
     */
    int insertSelective(UserInit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_init
     *
     * @mbg.generated
     */
    List<UserInit> selectByExample(UserInitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_init
     *
     * @mbg.generated
     */
    UserInit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_init
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserInit record, @Param("example") UserInitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_init
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserInit record, @Param("example") UserInitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_init
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserInit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_init
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInit record);
}